application: appspotid
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest

handlers:

- url: /portal
  script: portal.app
  secure: always

- url: /clean
  script: clean.app
  secure: always
  login: admin

- url: /clean_guesscnt
  script: clean_guesscnt.app
  secure: always
  login: admin

- url: /rekey
  script: rekey.app
  secure: always
